/* global module */
module.exports = function (grunt) {
    'use strict';
    grunt.initConfig({
        autoprefixer: {

            // if you have specified only the `src` param, the destination will be set automatically,
            // so source files will be overwritten
            no_dest: {
                src: 'style.css' // globbing is also possible here
            },
            options: {
                browsers: ['last 2 version', 'ie 8', 'ie 9']
            },
            sourcemap: {
                options: {
                    map: true
                },
                src: 'style.css',
                dest: 'style.css' // -> dest/css/file.css, dest/css/file.css.map
            },
        },

        sass: {
            dist: {
                options: {
                    sourcemap: true, // [true|false] (needs sass 3.3.0, gem install sass--pre)
                    style: 'compressed', // [nested|compact|compressed|expanded]
                    trace: true,
                    // precision: 8,
                    // compass: false, // can be true, config.rb should be in the same dir as Gruntfile.js
                    debugInfo: false, // if you're using FireSass Firebug plugin
                    // lineNumbers: true, // attache the line numbers in the generated css
                    // loadPath: true, // attach the source file path into the css
                    // require: [], // require ruby libraries (specify version numbers, et al)
                    // cacheLocation: '.sass-cache', // if you want to change the cache location
                    // noCache: false, // if you don't want to use the .sass-cache
                    // banner: 'Generated by Awesome' // prepend the specified string to the output file. Licensing
                },
                files: {
                    'style.css': 'sass/style.sass'
                }
            },
            admin: {
                options: {
                    sourcemap: true, // [true|false] (needs sass 3.3.0, gem install sass--pre)
                    style: 'compressed', // [nested|compact|compressed|expanded]
                    trace: true,
                    // precision: 8,
                    // compass: false, // can be true, config.rb should be in the same dir as Gruntfile.js
                    debugInfo: false, // if you're using FireSass Firebug plugin
                    // lineNumbers: true, // attache the line numbers in the generated css
                    // loadPath: true, // attach the source file path into the css
                    // require: [], // require ruby libraries (specify version numbers, et al)
                    // cacheLocation: '.sass-cache', // if you want to change the cache location
                    // noCache: false, // if you don't want to use the .sass-cache
                    // banner: 'Generated by Awesome' // prepend the specified string to the output file. Licensing
                },
                files: {
                    'functions/admin/es-admin-styles.css': 'functions/admin/sass/admin.sass'
                }
            }
        },
        uglify: {
            dist: {
                files: {
                    'js/app.min.js': [
                        'js/vendor/custom.modernizr.js',
                        'js/foundation/*.js',
                        'js/plugins/**/*.js'
                    ]
                }
            }
        },
        jshint: {
            files: ['js/**/*.js'],
            options: {
                jshintrc: '.jshintrc',
                ignores: [
                    'js/vendor/custom.modernizr.js',
                    'js/foundation/*.js',
                    'js/app.min.js'
                ]
            }
        },
        watch: {
            css: {
                files: 'sass/**/*.sass',
                tasks: ['sass:dist', 'autoprefixer'],
                options: {
                    spawn: true
                }
            },
            js: {
                files: ['js/**/*.js', '!js/app.min.js'],
                tasks: ['jshint', 'uglify'],
                options: {
                    spawn: true
                }
            },
            admincss: {
                files: 'functions/admin/sass/**/*.sass',
                tasks: ['sass:admin'],
                options: {
                    spawn: true
                }
            }
        },
        notify: {
            watch: {
                options: {
                    title: 'Task Complete',  // optional
                    message: 'SASS and Uglify finished running', //required
                }
            }
        },
        tasks: ['autoprefixer']
    });

    grunt.loadNpmTasks('grunt-autoprefixer');
    grunt.loadNpmTasks('grunt-contrib-sass');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-jshint');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-notify');
    grunt.registerTask('default', ['watch']);
    grunt.task.run('notify');
};
