module.exports = function(grunt) {
  grunt.initConfig({
    sass: {
      dist: {
        options: {
          sourcemap: true, // [true|false] (needs sass 3.3.0, gem install sass--pre)
          style: 'compressed', // [nested|compact|compressed|expanded]
          trace: true,
          // precision: 8,
          // compass: false, // can be true, config.rb should be in the same dir as Gruntfile.js
          debugInfo: true, // if you're using FireSass Firebug plugin
          // lineNumbers: true, // attache the line numbers in the generated css
          // loadPath: true, // attach the source file path into the css
          // require: [], // require ruby libraries (specify version numbers, et al)
          // cacheLocation: '.sass-cache', // if you want to change the cache location
          // noCache: false, // if you don't want to use the .sass-cache
          // banner: 'Generated by Awesome' // prepend the specified string to the output file. Licensing
        },
        files: {
          'style.css': 'sass/style.sass'
        }
      }
    },
    watch: {
      files: 'sass/*.sass',
      tasks: ['sass'],
      options: {
        spawn: true
      }
    }
  });
  grunt.loadNpmTasks('grunt-contrib-sass');
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.registerTask('default', ['watch']);
};
